version: "3.9"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - "./:/remix-practice"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
